Mappings:
  RegionMap:
    'ap-northeast-1':
      AMI: 'ami-0f310fced6141e627'
    'ap-southeast-1':
      AMI: 'ami-00b8d9cb8a7161e41'
Resources:
  MyWaitHandle: 
    Type: AWS::CloudFormation::WaitConditionHandle 
  MyWaitCondition: 
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: AutoScalingGroup
    Properties:
      Handle: 
        Ref: "MyWaitHandle" 
      Timeout: "300" 
      Count: 3
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      LaunchConfigurationName:
        Ref: LaunchConfig
      DesiredCapacity: '3'
      MinSize: '1'
      MaxSize: '4'
  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: t2.micro
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum update -y aws-cfn-bootstrap
            - |
              # Signal the status from cfn-init
            - '/opt/aws/bin/cfn-signal -e 0 -r "Instance Creation Complete" '
            - ''''
            - !Ref MyWaitHandle
            - |
              '
