version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-demo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1atvkbrimmtfv"
s3_prefix = "aws-sam-demo-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"