AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nest example: main'
Parameters:
  VPCCIDR: 
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: VPC CIDR Block (eg 10.0.0.0/16)
    Type: String
Resources:
  NetworkStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://tnobe-devops-mod2-examples.s3-ap-northeast-1.amazonaws.com/nest_network_template.yaml
      Parameters:
        CIDR: !Ref VPCCIDR
  AppTier:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: "NetworkStack"
    Properties:
      TemplateURL: https://tnobe-devops-mod2-examples.s3-ap-northeast-1.amazonaws.com/nest_apptier_template.yaml
      Parameters:
        VPCId: !GetAtt NetworkStack.Outputs.VPCId
Outputs:
  VPCId:
    Description: 'ID for new VPC'
    Value: !GetAtt NetworkStack.Outputs.VPCId
